default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: 'test_shopify'